<?php
// $Id$

/**
* VP-Core is a Full Featured, Webservice Oriented Media Management and
* Distribution platform (http://www.vpcore.nl)
*
* Copyright (C) 2009 Kennisnet (http://www.kennisnet.nl)
*
* VP-Core is based on the open source Drupal platform and was originally
* developed by Madcap BV (http://www.madcap.nl)
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 as
* published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License along
* with this program; if not, you can find it at:
* http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
*/

/**
 * @file
 * This module is an extension to mediamosa_media module. Provides a video content type.
 * Using a field declared in mediamosa_media, works in pair with the mediamosa_views_browser module
 *
 */

/**
 * Implementation of hook_node_info().
 */
function mediamosa_videocontent_node_info() {
  return array(
    'mediamosa_videocontent' => array(
      'name' => t('Mediamosa Video'),
      'module' => 'mediamosa_videocontent',
      'description' => "Content type with a video field allows your file to be uploaded to Mediamosa.",
    )
  );
}

/**
 * Implementation of hook_perm().
 */
function mediamosa_videocontent_perm() {
  return array('create mediamosa_videocontent', 'edit mediamosa_videocontent', 'edit own mediamosa_videocontent');
}

/**
 * Implementation of hook_access().
 */
function mediamosa_videocontent_access($op, $node) {
  global $user;

  if ($op == 'create') {
    return user_access('create mediamosa_videocontent');
  }

  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own mediamosa_videocontent') && ($user->uid == $node->uid)) {
      return TRUE;
    }

    if (user_access('edit mediamosa_videocontent')) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_form().
 */
function mediamosa_videocontent_form(&$node, $form_state) {
  $type = node_get_types('type', $node);

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -5
  );

  $form['body_filter']['body'] = array(
    '#type' => 'textarea',
    '#title' => check_plain($type->body_label),
    '#default_value' => $node->body,
    '#required' => FALSE
  );

  $form['body_filter']['filter'] = filter_form($node->format);



  return $form;
}

/**
 * Implementation of hook_help().
 */
function aa_mediamosa_videocontent_help($path, $arg) {
  switch ($path) {
    case 'admin/help#mediamosa_videocontent':
      return '<p>' . t('There must be help info!') . '</p>';
      break;
  }
}
