<?php
/**
 * @file
 * The MediaMosa Construction Kit module.
 */

// Configuration administrator permission.
define('MEDIAMOSA_CK_PERMISSION_ADMIN_CONFIGURATION', 'mediamosa-ck admin configuration');
define('MEDIAMOSA_CK_PERMISSION_ADD_MEDIA', 'add media to mediamosa');

/**
 * Implements hook_permission().
 */
function mediamosa_ck_permission() {
  return array(
    MEDIAMOSA_CK_PERMISSION_ADMIN_CONFIGURATION => array(
      'title' => t('Change MediaMosa construction kit configuration.'),
      'description' => t('Users with this permission can change the MediaMosa Construction Kit configuration.'),
    ),
    MEDIAMOSA_CK_PERMISSION_ADD_MEDIA =>  array(
      'title' => t('Add media to mediamosa.'),
      'description' => t('Users with this permission can add media to mediamosa.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mediamosa_ck_menu() {
  $items = array();

  $items['admin/config/media/mediamosa_ck/config'] = array(
    'title' => 'MediaMosa construction kit',
    'description' => 'Configuration settings of the MediaMosa Construction Kit.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_ck_configuration_form'),
    'access arguments' => array(MEDIAMOSA_CK_PERMISSION_ADMIN_CONFIGURATION),
    'file' => 'mediamosa_ck.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_date_formats().
 */
function mediamosa_ck_date_format_types() {
  // Define the MediaMosa CK date format types.
  return array(
    'mediamosa_ck_normal' => t('MediaMosa Site Builder - Normal'),
    'mediamosa_ck_mf_duration' => t('MediaMosa Site Builder - Mediafile duration'),
  );
}

/**
 * Implements hook_date_formats().
 */
function mediamosa_ck_date_formats() {
  return array(
    array(
      'type' => 'mediamosa_ck_normal',
      'format' => 'd-m-Y',
    ),
    array(
      'type' => 'mediamosa_ck_normal',
      'format' => 'm-d-Y',
      'locales' => array('en', 'en-us'),
    ),
    array(
      'type' => 'mediamosa_ck_mf_duration',
      'format' => 'i:s',
      'locales' => array('en', 'en-us'),
    ),
    array(
      'type' => 'mediamosa_ck_mf_duration',
      'format' => 'H:i:s',
      'locales' => array('en', 'en-us'),
    ),
  );
}
