<?php
// $Id: mediamosa_views_browser.module

/**
 * @file
 * Provide our View to work with mediamosa_media module.
 */

/**
 * Implementation of hook_init().
 */
function mediamosa_views_browser_init() {
  drupal_add_css(drupal_get_path('module', 'mediamosa_views_browser') . '/mediamosa_views_browser.css');
}

/**
 * Implementation of hook_views_api().
 */
function mediamosa_views_browser_views_api() {
  return array(
    'api' => 2,
  );
}

