<?php
/**
 * @file
 * Mediamosa ck views module.
 */

/**
 * Implements hook_views_api().
 */
function mediamosa_ck_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_plugins().
 */
function mediamosa_ck_views_views_plugins() {
  return array(
    'module' => 'mediamosa_ck_views',
    'query' => array(
      'mediamosa_asset_get' => array(
        'title' => t('MediaMosa Asset Get'),
        'help' => t('This view can be used to display one single MediaMosa asset.'),
        'handler' => 'mediamosa_ck_views_rest_asset_get',
      ),
      'mediamosa_assets_get' => array(
        'title' => t('MediaMosa Assets'),
        'help' => t('This view can be used to retrieve one or more specific assets.'),
        'handler' => 'mediamosa_ck_views_rest_assets_get',
      ),
      'mediamosa_asset_featured' => array(
        'title' => t('MediaMosa Asset Featured'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_asset_featured',
      ),
      'mediamosa_asset_new' => array(
        'title' => t('MediaMosa Asset New'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_asset_new',
      ),
      'mediamosa_asset_popular' => array(
        'title' => t('MediaMosa Asset Popular'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_asset_popular',
      ),
      'mediamosa_asset_search' => array(
        'title' => t('MediaMosa Asset Search'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_asset_search',
      ),
      'mediamosa_assets_in_collection' => array(
        'title' => t('MediaMosa Assets in Collection'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_assets_in_collection',
      ),
      'mediamosa_collection_search' => array(
        'title' => t('MediaMosa Collection Search'),
        'help' => t('Query will be run on MediaMosa REST interface and processed back for usage in views.'),
        'handler' => 'mediamosa_ck_views_rest_collection_search',
      ),
      'mediamosa_collection_get' => array(
        'title' => t('MediaMosa Collection Get'),
        'help' => t('Will retrieve the collection data from MediaMosa.'),
        'handler' => 'mediamosa_ck_views_rest_collection_get',
      ),
      'mediamosa_collection_asset' => array(
        'title' => t('MediaMosa Collection Assets'),
        'help' => t('Will retrieve the assets within the collection.'),
        'handler' => 'mediamosa_ck_views_rest_collection_asset',
      ),
    ),
  );
}

/**
 * Implements hook_views_data().
 */
function mediamosa_ck_views_views_data() {
  // Asset get.
  $data['mediamosa_asset_get'] = mediamosa_ck_views_rest_asset_get::get_views_data('MediaMosa: Asset Detail', 'mediamosa_asset_get');

  // Asset get.
  $data['mediamosa_ck_views_rest_assets_get'] = mediamosa_ck_views_rest_assets_get::get_views_data('MediaMosa: Specific assets', 'mediamosa_ck_views_rest_assets_get');

  // Asset featured.
  $data['mediamosa_asset_featured'] = mediamosa_ck_views_rest_asset_featured::get_views_data('MediaMosa: Asset Featured', 'mediamosa_asset_featured');

  // Asset search REST call (/asset).
  $data['mediamosa_asset_search'] = mediamosa_ck_views_rest_asset_search::get_views_data('MediaMosa: Asset Search', 'mediamosa_asset_search');

  // Asset search REST call (/asset).
  $data['mediamosa_assets_in_collection'] = mediamosa_ck_views_rest_assets_in_collection::get_views_data('MediaMosa: Assets in Collection', 'mediamosa_assets_in_collection');

  // Asset new.
  $data['mediamosa_asset_new'] = mediamosa_ck_views_rest_asset_new::get_views_data('MediaMosa: Asset New', 'mediamosa_asset_new');

  // Asset popular.
  $data['mediamosa_asset_popular'] = mediamosa_ck_views_rest_asset_popular::get_views_data('MediaMosa: Asset Popular', 'mediamosa_asset_popular');

  // Collection search REST call (/collection).
  $data['mediamosa_collection_search'] = mediamosa_ck_views_rest_collection_search::get_views_data('MediaMosa: Collection Search', 'mediamosa_collection_search');

  // Collection get REST call (/collection/coll_id).
  $data['mediamosa_collection_get'] = mediamosa_ck_views_rest_collection_get::get_views_data('MediaMosa: Collection Get', 'mediamosa_collection_get');

  // Collection assets.
  $data['mediamosa_collection_asset'] = mediamosa_ck_views_rest_collection_asset::get_views_data('MediaMosa: Collection Assets', 'mediamosa_collection_asset');

  return $data;
}

/**
 * Implements hook_theme().
 */
function mediamosa_ck_views_theme() {
  return array(
    'mediamosa_ck_views_theme_asset_mediafiles' => array(
      'variables' => array(
        'mediafiles' => array(),
        'asset_path' => 'asset/detail/[asset_id]/[mediafile_id]',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_asset_collections' => array(
      'variables' => array(
        'collections' => array(),
        'collection_path' => 'collection/detail/[coll_id]',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_asset_metadata' => array(
      'variables' => array(
        'metadata' => array(),
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_asset_technical_metadata' => array(
      'variables' => array(
        'technical_metadata' => array(),
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_collection_actions' => array(
      'variables' => array(
        'coll_id' => '',
        'action_path_edit' => 'collection/edit/[coll_id]',
        'action_path_delete' => 'collection/delete/[coll_id]',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_asset_actions' => array(
      'variables' => array(
        'asset_id' => '',
        'action_path_edit' => 'asset/edit/[asset_id]',
        'action_path_delete' => 'asset/delete/[asset_id]',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_theme_owner' => array(
      'variables' => array(
        'uid' => 0,
        'name' => '',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_player_image' => array(
      'variables' => array(
        'error_code' => 0,
        'mediafile_id' => '',
        'asset_id' => '',
        'width' => '',
        'height' => '',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
    'mediamosa_ck_views_player' => array(
      'variables' => array(
        'response' => '',
        'mime_type' => '',
      ),
      'file' => 'mediamosa_ck_views.theme.inc',
    ),
  );
}
